version: '3.8'

services:
  # Servicio de PHP
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: fitplanner
        uid: 1000
    container_name: fitplanner-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:80"
    networks:
      - fitplanner-network

  # Servicio de Nginx
  nginx:
    image: nginx:alpine
    container_name: fitplanner-nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - fitplanner-network

  # Servicio de Redis
  redis:
    image: redis:alpine
    container_name: fitplanner-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - fitplanner-network

networks:
  fitplanner-network:
    driver: bridge
