version: '3.8'

services:
  # Servicio de PHP
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: fitplanner
        uid: 1000
    container_name: fitplanner-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      - DB_HOST=${MYSQLHOST}
      - DB_PORT=${MYSQLPORT}
      - DB_DATABASE=${MYSQLDATABASE}
      - DB_USERNAME=${MYSQLUSER}
      - DB_PASSWORD=${MYSQLPASSWORD}
    volumes:
      - ./:/var/www
    networks:
      - fitplanner-network

  # Servicio de Nginx
  nginx:
    image: nginx:alpine
    container_name: fitplanner-nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - fitplanner-network

  # Servicio de Redis
  redis:
    image: redis:alpine
    container_name: fitplanner-redis
    restart: unless-stopped
    networks:
      - fitplanner-network

networks:
  fitplanner-network:
    driver: bridge
