[phases.setup]
nixPkgs = [
    "nodejs",
    "php82",
    "php82Packages.composer"
]

[phases.install]
cmds = [
    "composer install",
    "npm ci",
    "npm run build",
    "php artisan key:generate --force"
]

[phases.build]
cmds = [
    "php artisan config:cache",
    "php artisan route:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT}" 