[phases.setup]
nixPkgs = [
    "nodejs",
    "php82",
    "php82Packages.composer",
    "php82Packages.pdo_mysql",
    "php82Packages.mysql",
    "mysql80"
]

[phases.install]
cmds = [
    "composer install --no-interaction --optimize-autoloader",
    "npm install",
    "npm run build"
]

[phases.build]
cmds = [
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "php artisan migrate --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT" 