[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=${PORT}"
healthcheckPath = "/"

[deploy.env]
APP_ENV = "production"
APP_DEBUG = "false"
PHP_MEMORY_LIMIT = "512M"

[deploy.buildCommand]
steps = [
    "cp .env.example .env",
    "composer install --no-dev --optimize-autoloader",
    "npm ci",
    "npm run build",
    "php artisan key:generate --force",
    "php artisan storage:link",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
] 