[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.env]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_LEVEL = "debug"
SESSION_DRIVER = "file"
CACHE_DRIVER = "file"
QUEUE_CONNECTION = "sync"

[deploy.healthcheck]
path = "/"
initialDelay = 10
interval = 30
timeout = 5
maxRetries = 3 