[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/login"
healthcheckTimeout = 200
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[service]
internal_port = 9000 